###
GET http://localhost:8080/api/reservation/list

###
POST http://localhost:8080/api/reservation/create
Content-Type: application/json

{
  "roomNumber": "r101",
  "startDateTime": "2023-11-08T00:00:000",
    "endDateTime": "2023-11-10T00:00:000",
  "user": {
    "id": 1
  },
  "hotel": {
    "id": 1
  }
}

###
PUT http://localhost:8080/api/reservation/update
Content-Type: application/json

{
  "id": 1,
  "status": "PAID",
  "user": {
    "id": 1
  },
  "hotel": {
    "id": 1
  }
}

###
DELETE http://localhost:8080/api/reservation/delete/{id}